ALTER TABLE tasks ADD COLUMN scan_verdict TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN scan_scanner TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN scan_at TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN waiting_callback INTEGER NOT NULL DEFAULT 0;
