const state={status:"",page:1,pageSize:20,total:0,selected:""};
const $=id=>document.getElementById(id);const tasks=$("tasks"),detail=$("detail"),toast=$("toast");
function escapeHTML(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KiB`;return `${(n/1048576).toFixed(1)} MiB`;}
function formatTime(v){if(!v)return "—";return new Date(v).toLocaleString("zh-CN",{hour12:false});}
function showToast(message,error=false){toast.textContent=message;toast.className=`toast${error?" error":""}`;setTimeout(()=>toast.classList.add("hidden"),3000);}
async function api(url,options={}){const res=await fetch(url,options);let body={};try{body=await res.json();}catch{}if(!res.ok)throw new Error(`${body.code||res.status}: ${body.message||"请求失败"}`);return body;}
async function loadTasks(){const q=new URLSearchParams({page:state.page,page_size:state.pageSize});if(state.status)q.set("status",state.status);try{const data=await api(`/api/v1/tasks?${q}`);state.total=data.total;renderTasks(data.items);$("count").textContent=`共 ${data.total} 个任务`;const pages=Math.max(1,Math.ceil(data.total/state.pageSize));$("page").textContent=`第 ${state.page} / ${pages} 页`;$("prev").disabled=state.page<=1;$("next").disabled=state.page>=pages;}catch(err){tasks.innerHTML=`<tr><td colspan="6" class="empty">${escapeHTML(err.message)}</td></tr>`;}}
function renderTasks(items){if(!items.length){tasks.innerHTML='<tr><td colspan="6" class="empty">暂无任务</td></tr>';return;}tasks.innerHTML=items.map(t=>`<tr><td class="task-name"><strong>${escapeHTML(t.id)}</strong><span>${escapeHTML(t.filename)}</span></td><td>${formatBytes(t.size)}</td><td>${escapeHTML(t.stage)}</td><td><span class="badge ${t.status}">${t.status}</span></td><td>${formatTime(t.created_at)}</td><td><div class="actions"><button data-view="${t.id}">详情</button>${t.status==="FAILED"?`<button class="retry" data-retry="${t.id}">重试</button>`:""}</div></td></tr>`).join("");}
async function loadDetail(id){state.selected=id;detail.innerHTML='<div class="empty">加载中…</div>';try{const data=await api(`/api/v1/tasks/${encodeURIComponent(id)}`);renderDetail(data.task,data.events);}catch(err){detail.innerHTML=`<div class="empty">${escapeHTML(err.message)}</div>`;}}
function renderDetail(t,events){const metrics=[["任务 ID",t.id],["文件",t.filename],["大小",formatBytes(t.size)],["状态",t.status],["当前阶段",t.stage],["尝试 / 手动重试",`${t.attempts} / ${t.retry_count}`],["SHA-256",t.sha256],["MIME",t.mime],["扫描判定",t.scan_verdict||"—"]];detail.innerHTML=`<div class="detail-grid">${metrics.map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${escapeHTML(v)}</strong></div>`).join("")}</div>${t.error_message?`<h3>错误</h3><p>${escapeHTML(t.error_code)} · ${escapeHTML(t.error_message)}</p>`:""}${t.extracted_summary?`<h3>提取摘要</h3><pre class="summary">${escapeHTML(t.extracted_summary)}</pre>`:""}<h3>阶段时间线</h3><div class="timeline">${events.length?events.map(e=>`<div class="event ${e.status}"><strong>${escapeHTML(e.stage)} · ${escapeHTML(e.status)}</strong><p>${escapeHTML(e.message)}</p><small>第 ${e.attempt} 次 · ${formatTime(e.created_at)}</small></div>`).join(""):'<div class="empty">暂无事件</div>'}</div>`;}
async function retryTask(id){try{await api(`/api/v1/tasks/${encodeURIComponent(id)}/retry`,{method:"POST"});showToast("任务已重新入队");await loadTasks();await loadDetail(id);}catch(err){showToast(err.message,true);await loadTasks();}}
$("upload-form").addEventListener("submit",e=>{e.preventDefault();const file=$("file").files[0];if(!file)return showToast("请先选择文件",true);if(file.size>10*1024*1024)return showToast("文件超过 10 MiB",true);const form=new FormData();form.append("file",file);const xhr=new XMLHttpRequest();xhr.open("POST","/api/v1/files");$("progress-wrap").classList.remove("hidden");xhr.upload.onprogress=event=>{if(event.lengthComputable)$("progress").style.width=`${event.loaded/event.total*100}%`;};xhr.onload=async()=>{let body={};try{body=JSON.parse(xhr.responseText);}catch{}if(xhr.status===201){$("notice").textContent=`任务 ${body.id} 已创建`;showToast("上传成功");state.page=1;await loadTasks();await loadDetail(body.id);}else showToast(`${body.code||xhr.status}: ${body.message||"上传失败"}`,true);setTimeout(()=>$("progress-wrap").classList.add("hidden"),600);};xhr.onerror=()=>showToast("网络错误",true);xhr.send(form);});
$("file").addEventListener("change",e=>{$("file-label").textContent=e.target.files[0]?.name||"选择文件或拖放到此处";});
const drop=$("drop-zone");["dragenter","dragover"].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add("drag");}));["dragleave","drop"].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove("drag");}));drop.addEventListener("drop",e=>{if(e.dataTransfer.files.length){$("file").files=e.dataTransfer.files;$("file-label").textContent=e.dataTransfer.files[0].name;}});
tasks.addEventListener("click",e=>{const view=e.target.dataset.view,retry=e.target.dataset.retry;if(view)loadDetail(view);if(retry)retryTask(retry);});
$("filters").addEventListener("click",e=>{if(e.target.dataset.status===undefined)return;document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");state.status=e.target.dataset.status;state.page=1;loadTasks();});
$("refresh").onclick=()=>{loadTasks();if(state.selected)loadDetail(state.selected);};$("prev").onclick=()=>{if(state.page>1){state.page--;loadTasks();}};$("next").onclick=()=>{if(state.page*state.pageSize<state.total){state.page++;loadTasks();}};$("close-detail").onclick=()=>{state.selected="";detail.innerHTML='<div class="empty">尚未选择任务</div>';};
loadTasks();setInterval(()=>{if(!document.hidden){loadTasks();if(state.selected)loadDetail(state.selected);}},3000);
